version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Asesamo
      MYSQL_DATABASE: fitco_chat
      MYSQL_USER: fitco_user
      MYSQL_PASSWORD: fitco_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
